- name: debug demo
  hosts: all 
  vars: 
    URL: cloudblitz.in
  vars_files:
    - ./file.txt
  tasks:
    - debug:
       msg: Hello World,  {{ URL}}
      vars:
         URL: local.cloudblitz.in
    - debug:
          msg: Hello world, {{ URL }}



       #global variable
       #task/local
       #

   # priority of global variables


   #cmd line var #ansible-playbook -e URL=cli.cloudblitz.in -u ubuntu --private-key=/home/ubuntu/id_ansible.pem -i./hosts ./variable.yaml
   #local
   #file
   #global
   
   